
[build]
publish = "dist"
command = "pnpm run build"

[build.environment]
NODE_VERSION = "22"
PLAYWRIGHT_BROWSERS_PATH = "0"


[[redirects]]
from = "/2025/react-next/src"
to = "https://github.com/nirtamir2/talks/tree/main/2025-06-25"
status = 302

[[redirects]]
from = "2025-06-25"
to = "https://talks.nirtamir.com/2025/react-next/"
status = 301

[[redirects]]
from = "/2025/react-next/*"
to = "/2025/react-next/index.html"
status = 200

[[redirects]]
from = "/2025/node-tlv/src"
to = "https://github.com/nirtamir2/talks/tree/main/2025-06-26"
status = 302

[[redirects]]
from = "2025-06-26"
to = "https://talks.nirtamir.com/2025/node-tlv/"
status = 301

[[redirects]]
from = "/2025/node-tlv/*"
to = "/2025/node-tlv/index.html"
status = 200

[[redirects]]
from = "/"
to = "https://nirtamir.com/talks"
status = 302
