/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DemoRouteImport } from './routes/demo/route'
import { Route as DemoIndexImport } from './routes/demo/index'
import { Route as DemoWowImport } from './routes/demo/wow'
import { Route as DemoMaterialImport } from './routes/demo/material'
import { Route as DemoGeometryImport } from './routes/demo/geometry'
import { Route as DemoEmptyImport } from './routes/demo/empty'
import { Route as DemoCubeImport } from './routes/demo/cube'
import { Route as DemoBasicImport } from './routes/demo/basic'

// Create/Update Routes

const DemoRouteRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRoute,
} as any)

const DemoIndexRoute = DemoIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRouteRoute,
} as any)

const DemoWowRoute = DemoWowImport.update({
  id: '/wow',
  path: '/wow',
  getParentRoute: () => DemoRouteRoute,
} as any)

const DemoMaterialRoute = DemoMaterialImport.update({
  id: '/material',
  path: '/material',
  getParentRoute: () => DemoRouteRoute,
} as any)

const DemoGeometryRoute = DemoGeometryImport.update({
  id: '/geometry',
  path: '/geometry',
  getParentRoute: () => DemoRouteRoute,
} as any)

const DemoEmptyRoute = DemoEmptyImport.update({
  id: '/empty',
  path: '/empty',
  getParentRoute: () => DemoRouteRoute,
} as any)

const DemoCubeRoute = DemoCubeImport.update({
  id: '/cube',
  path: '/cube',
  getParentRoute: () => DemoRouteRoute,
} as any)

const DemoBasicRoute = DemoBasicImport.update({
  id: '/basic',
  path: '/basic',
  getParentRoute: () => DemoRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRoute
    }
    '/demo/basic': {
      id: '/demo/basic'
      path: '/basic'
      fullPath: '/demo/basic'
      preLoaderRoute: typeof DemoBasicImport
      parentRoute: typeof DemoRouteImport
    }
    '/demo/cube': {
      id: '/demo/cube'
      path: '/cube'
      fullPath: '/demo/cube'
      preLoaderRoute: typeof DemoCubeImport
      parentRoute: typeof DemoRouteImport
    }
    '/demo/empty': {
      id: '/demo/empty'
      path: '/empty'
      fullPath: '/demo/empty'
      preLoaderRoute: typeof DemoEmptyImport
      parentRoute: typeof DemoRouteImport
    }
    '/demo/geometry': {
      id: '/demo/geometry'
      path: '/geometry'
      fullPath: '/demo/geometry'
      preLoaderRoute: typeof DemoGeometryImport
      parentRoute: typeof DemoRouteImport
    }
    '/demo/material': {
      id: '/demo/material'
      path: '/material'
      fullPath: '/demo/material'
      preLoaderRoute: typeof DemoMaterialImport
      parentRoute: typeof DemoRouteImport
    }
    '/demo/wow': {
      id: '/demo/wow'
      path: '/wow'
      fullPath: '/demo/wow'
      preLoaderRoute: typeof DemoWowImport
      parentRoute: typeof DemoRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexImport
      parentRoute: typeof DemoRouteImport
    }
  }
}

// Create and export the route tree

interface DemoRouteRouteChildren {
  DemoBasicRoute: typeof DemoBasicRoute
  DemoCubeRoute: typeof DemoCubeRoute
  DemoEmptyRoute: typeof DemoEmptyRoute
  DemoGeometryRoute: typeof DemoGeometryRoute
  DemoMaterialRoute: typeof DemoMaterialRoute
  DemoWowRoute: typeof DemoWowRoute
  DemoIndexRoute: typeof DemoIndexRoute
}

const DemoRouteRouteChildren: DemoRouteRouteChildren = {
  DemoBasicRoute: DemoBasicRoute,
  DemoCubeRoute: DemoCubeRoute,
  DemoEmptyRoute: DemoEmptyRoute,
  DemoGeometryRoute: DemoGeometryRoute,
  DemoMaterialRoute: DemoMaterialRoute,
  DemoWowRoute: DemoWowRoute,
  DemoIndexRoute: DemoIndexRoute,
}

const DemoRouteRouteWithChildren = DemoRouteRoute._addFileChildren(
  DemoRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/demo': typeof DemoRouteRouteWithChildren
  '/demo/basic': typeof DemoBasicRoute
  '/demo/cube': typeof DemoCubeRoute
  '/demo/empty': typeof DemoEmptyRoute
  '/demo/geometry': typeof DemoGeometryRoute
  '/demo/material': typeof DemoMaterialRoute
  '/demo/wow': typeof DemoWowRoute
  '/demo/': typeof DemoIndexRoute
}

export interface FileRoutesByTo {
  '/demo/basic': typeof DemoBasicRoute
  '/demo/cube': typeof DemoCubeRoute
  '/demo/empty': typeof DemoEmptyRoute
  '/demo/geometry': typeof DemoGeometryRoute
  '/demo/material': typeof DemoMaterialRoute
  '/demo/wow': typeof DemoWowRoute
  '/demo': typeof DemoIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/demo': typeof DemoRouteRouteWithChildren
  '/demo/basic': typeof DemoBasicRoute
  '/demo/cube': typeof DemoCubeRoute
  '/demo/empty': typeof DemoEmptyRoute
  '/demo/geometry': typeof DemoGeometryRoute
  '/demo/material': typeof DemoMaterialRoute
  '/demo/wow': typeof DemoWowRoute
  '/demo/': typeof DemoIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/demo'
    | '/demo/basic'
    | '/demo/cube'
    | '/demo/empty'
    | '/demo/geometry'
    | '/demo/material'
    | '/demo/wow'
    | '/demo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/demo/basic'
    | '/demo/cube'
    | '/demo/empty'
    | '/demo/geometry'
    | '/demo/material'
    | '/demo/wow'
    | '/demo'
  id:
    | '__root__'
    | '/demo'
    | '/demo/basic'
    | '/demo/cube'
    | '/demo/empty'
    | '/demo/geometry'
    | '/demo/material'
    | '/demo/wow'
    | '/demo/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  DemoRouteRoute: typeof DemoRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  DemoRouteRoute: DemoRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/demo"
      ]
    },
    "/demo": {
      "filePath": "demo/route.tsx",
      "children": [
        "/demo/basic",
        "/demo/cube",
        "/demo/empty",
        "/demo/geometry",
        "/demo/material",
        "/demo/wow",
        "/demo/"
      ]
    },
    "/demo/basic": {
      "filePath": "demo/basic.tsx",
      "parent": "/demo"
    },
    "/demo/cube": {
      "filePath": "demo/cube.tsx",
      "parent": "/demo"
    },
    "/demo/empty": {
      "filePath": "demo/empty.tsx",
      "parent": "/demo"
    },
    "/demo/geometry": {
      "filePath": "demo/geometry.tsx",
      "parent": "/demo"
    },
    "/demo/material": {
      "filePath": "demo/material.tsx",
      "parent": "/demo"
    },
    "/demo/wow": {
      "filePath": "demo/wow.tsx",
      "parent": "/demo"
    },
    "/demo/": {
      "filePath": "demo/index.tsx",
      "parent": "/demo"
    }
  }
}
ROUTE_MANIFEST_END */
