/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DemoRouteImport } from './routes/demo/route'
import { Route as DemoWowImport } from './routes/demo/wow'
import { Route as DemoEmptyImport } from './routes/demo/empty'
import { Route as DemoBasicImport } from './routes/demo/basic'

// Create/Update Routes

const DemoRouteRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRoute,
} as any)

const DemoWowRoute = DemoWowImport.update({
  id: '/wow',
  path: '/wow',
  getParentRoute: () => DemoRouteRoute,
} as any)

const DemoEmptyRoute = DemoEmptyImport.update({
  id: '/empty',
  path: '/empty',
  getParentRoute: () => DemoRouteRoute,
} as any)

const DemoBasicRoute = DemoBasicImport.update({
  id: '/basic',
  path: '/basic',
  getParentRoute: () => DemoRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRoute
    }
    '/demo/basic': {
      id: '/demo/basic'
      path: '/basic'
      fullPath: '/demo/basic'
      preLoaderRoute: typeof DemoBasicImport
      parentRoute: typeof DemoRouteImport
    }
    '/demo/empty': {
      id: '/demo/empty'
      path: '/empty'
      fullPath: '/demo/empty'
      preLoaderRoute: typeof DemoEmptyImport
      parentRoute: typeof DemoRouteImport
    }
    '/demo/wow': {
      id: '/demo/wow'
      path: '/wow'
      fullPath: '/demo/wow'
      preLoaderRoute: typeof DemoWowImport
      parentRoute: typeof DemoRouteImport
    }
  }
}

// Create and export the route tree

interface DemoRouteRouteChildren {
  DemoBasicRoute: typeof DemoBasicRoute
  DemoEmptyRoute: typeof DemoEmptyRoute
  DemoWowRoute: typeof DemoWowRoute
}

const DemoRouteRouteChildren: DemoRouteRouteChildren = {
  DemoBasicRoute: DemoBasicRoute,
  DemoEmptyRoute: DemoEmptyRoute,
  DemoWowRoute: DemoWowRoute,
}

const DemoRouteRouteWithChildren = DemoRouteRoute._addFileChildren(
  DemoRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/demo': typeof DemoRouteRouteWithChildren
  '/demo/basic': typeof DemoBasicRoute
  '/demo/empty': typeof DemoEmptyRoute
  '/demo/wow': typeof DemoWowRoute
}

export interface FileRoutesByTo {
  '/demo': typeof DemoRouteRouteWithChildren
  '/demo/basic': typeof DemoBasicRoute
  '/demo/empty': typeof DemoEmptyRoute
  '/demo/wow': typeof DemoWowRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/demo': typeof DemoRouteRouteWithChildren
  '/demo/basic': typeof DemoBasicRoute
  '/demo/empty': typeof DemoEmptyRoute
  '/demo/wow': typeof DemoWowRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/demo' | '/demo/basic' | '/demo/empty' | '/demo/wow'
  fileRoutesByTo: FileRoutesByTo
  to: '/demo' | '/demo/basic' | '/demo/empty' | '/demo/wow'
  id: '__root__' | '/demo' | '/demo/basic' | '/demo/empty' | '/demo/wow'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  DemoRouteRoute: typeof DemoRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  DemoRouteRoute: DemoRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/demo"
      ]
    },
    "/demo": {
      "filePath": "demo/route.tsx",
      "children": [
        "/demo/basic",
        "/demo/empty",
        "/demo/wow"
      ]
    },
    "/demo/basic": {
      "filePath": "demo/basic.tsx",
      "parent": "/demo"
    },
    "/demo/empty": {
      "filePath": "demo/empty.tsx",
      "parent": "/demo"
    },
    "/demo/wow": {
      "filePath": "demo/wow.tsx",
      "parent": "/demo"
    }
  }
}
ROUTE_MANIFEST_END */
